### ISSUE TITLE
Style fix m.m

### ISSUE THREAD

**Issue by mikaelmattsson** [karlaugustsson/robot_challenge#1]
https://github.com/karlaugustsson/robot_challenge/blob/master/app/RobotChallenge/WarpPoint.php#L1

Allt under /app/ borde ligga under samma rootnamespace (`App`).
Vill du ha ett till namespace så lägg det i en egen katalog bredvid app.
Eller byt till `App\RobotChallenge`.

https://github.com/karlaugustsson/robot_challenge/blob/master/app/RobotChallenge/WarpPoint.php#L3-L9

`as Xxx` är overflödigt.
skriv `use RobotChallenge\Interfaces\GridObjectInterface;`
istället för `use RobotChallenge\Interfaces\GridObjectInterface as GridObjectInterface ;`

https://github.com/karlaugustsson/robot_challenge/blob/master/app/RobotChallenge/WarpPoint.php#L13-L17

Byt till camel case.

https://github.com/karlaugustsson/robot_challenge/blob/master/app/RobotChallenge/Grid.php#L80-L83

Position skulle kunna vara ett ”value-object”. Då behöver du inte kontrollera arrayen med positionArrayIsValid.

https://github.com/karlaugustsson/robot_challenge/blob/master/app/RobotChallenge/Interfaces/MoveableObjectInterface.php#L6-L8

But till camelCase på variabelnamn.

https://github.com/karlaugustsson/robot_challenge/blob/master/app/RobotChallenge/Robot.php#L48-L50

Att returnera false i kontruktorn har ingen poäng. `return` räcker om du vill stoppa metoden.
`ValidFacingDirection` borde bara `validFacingDirection`
Den borde kasta exception (se nästa punkt)

https://github.com/karlaugustsson/robot_challenge/blob/master/app/RobotChallenge/Robot.php#L304-L325

`return` direkt efter `throw` har ingen poäng.
metoderna kanske borde heta något i stil med `validateFacingDirection` istället för `validFacingDirection` och bara kasta exception och aldrig returnera något.
Jag hade nog inte kastat något exception alls inuti dessa metoder utan bara döpt dem till `isValidFacingDirection` och returnera `true`/`false`
sen kasta exception från metoden som använde dessa metoder. (se föregående punkt)

https://github.com/karlaugustsson/robot_challenge/blob/master/app/RobotChallenge/Robot.php#L332-L335

”Getters” borde börja med `get` t.ex. `getInventory`
### Generellt:
- Ta en titt på [PHPDoc](https://www.sitepoint.com/introduction-to-phpdoc/) för metoder och properties

```
    /**
     * @var Grid
     */
    protected $grid;

    [...]

    /**
     * Short explanation of what the method does.
     *
     * @return Grid
     * @throws NoGridObjectFoundException
     */
    public function getGrid()
    {
        if ($this->grid === null) {
            throw new NoGridObjectFoundException('No grid object has been set');
        }

        return $this->grid;
    }
```

**Comment by karlaugustsson** [comment]
har lite problem med camelcase https://github.com/karlaugustsson/robot_challenge/blob/master/app/RobotChallenge/Grid.php#L80-L83

vad jag anser så är funktionerna i  lower camleCase  eller skall dom vara i upper CamelCase?

**Comment by mikaelmattsson** [comment]
UPPERCASE
StudlyCaps
camelCase
under_score
lowercase

> - Class names MUST be declared in StudlyCaps.
> - Class constants MUST be declared in all upper case with underscore separators.
> - Method names MUST be declared in camelCase.

Källa:
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md

**Comment by mikaelmattsson** [comment]
För variables/properties har inte psr någon specifikation men än att man ska vara konsekvent.

Vi kör symfony:
http://programmers.stackexchange.com/questions/196416/whats-the-dominant-naming-convention-for-variables-in-php-camelcase-or-undersc

**Comment by karlaugustsson** [comment]
gott  jag märker att jag valt en del jobbiga namn ,  jobbar på att byta ut dom
